# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-15 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_auto_20170915_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, height_field=480, upload_to='images/category', width_field=1349),
        ),
    ]
